### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by kettanaito** [ludovitkapusta/react-easy-notifications#1]
* [notifications/index.js@5](https://github.com/escuriak/react-easy-notifications/blob/master/src/notification/index.js#L5) - Why extending over composition? Have you considered to have your custom class *using* EventEmitter, rather than extending it?

* [src/index.js@1](https://github.com/escuriak/react-easy-notifications/blob/master/src/index.js#L1) - You can also use `babel-plugin-transform-export-extensions` to be able to export modules without explicitly importing them.

It's hard to analyze other points since I don't understand the whole architecture.

Probably, a possible point from me is that when you base your solution on events, you may want to consider to get rid of the stateful components at all.

**Comment by ludovitkapusta** [comment]
Thank you for your issue.
As for your points, i like your ideas. Using EventEmitter is a lot better approach then extending it, i changed the logic here.
Also for importing and exporting modules, i changed my code for easier approach with the help of `babel-plugin-transform-export-extensions`

As for your part about getting rid of stateful components, i considered it, but to achieve the desired logic and aproach, for now, i am staying with the restful components.

**Comment by kettanaito** [comment]
@escuriak Probably, you can even use the React's context feature to communicate between the notification container and the places where you want to dispatch the notification. That way it would be based on callbacks, which is fine in the current situation. This way you can get rid of `EventEmitter` completely, shaving off another dependency from the library.

The only thing it would require is for notifications to be (indirect) children of the notification container. So it acts like their wrapper (similarly to `ReduxProvider`).

**Comment by ludovitkapusta** [comment]
Will surely look on this in the near future. Thank you for you ideas
