### ISSUE TITLE
Omit "build" directory in source files

### ISSUE THREAD

**Issue by kettanaito** [ludovitkapusta/react-easy-notifications#2]
I can suggest you to ignore "build" directory in `.gitignore`. You don't want to commit build to Git.

Instead, building the library must be in the `prepublishOnly` or `postinstall` hooks, which will be triggered at different points of interaction with your library and served to NPM or local `node_modules` respectively.

**Comment by ludovitkapusta** [comment]
i was thinking about this for some time, but i was missing some impulse to finally do it. so thank you for pointing this out. its done now.
